### PR TITLE
fix issue64 version1

### PR DESCRIPTION
**Pull request by olivernan**
This pull request working on issue64 by Yiyang. Already pass the local test.

### CODE REVIEW

**Comment by olivernan** [comment]
how to solve this conflicts if I already pushed.

**Comment by olivernan** [comment]
I resolve the conflicts manually. Please double check before merge with master. Thanks

**Comment by olivernan** [comment]
why after I resolved the conflicts using the GitHub website editor and committed it, I pulled the updated remote nanyy_divider_2 to my local nanyy_divider_2. The local log said Merge branch 'master' into nanyy_divider_2. **Remark ask next meeting

**Comment by xiaoyingpu** [comment]
@olivernan  What exactly did you do with the `nanyy_divider_2` branch? The diff shows 27 files changed but you probably only changed a few lines in divider.R? 

Also, can you write some unit tests for the `aes_checker()` function, try to have an example in pgog.Rmd,  and use more descriptive commit/pull request messages?

**Comment by olivernan** [comment]
> @olivernan What exactly did you do with the `nanyy_divider_2` branch? The diff shows 27 files changed but you probably only changed a few lines in divider.R?
> 
> Also, can you write some unit tests for the `aes_checker()` function, try to have an example in pgog.Rmd, and use more descriptive commit/pull request messages?

Ok, I will do that

**Comment by xiaoyingpu** [comment]
> > @olivernan What exactly did you do with the `nanyy_divider_2` branch? The diff shows 27 files changed but you probably only changed a few lines in divider.R?
> > Also, can you write some unit tests for the `aes_checker()` function, try to have an example in pgog.Rmd, and use more descriptive commit/pull request messages?
> 
> Ok, I will do that

BTW the diff is coming from some Windows end-of-line characters... make sure you have the right setting for end-of-line characters: 
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings. I just fixed the master branch in a commit

**Comment by olivernan** [comment]
> > > @olivernan What exactly did you do with the `nanyy_divider_2` branch? The diff shows 27 files changed but you probably only changed a few lines in divider.R?
> > > Also, can you write some unit tests for the `aes_checker()` function, try to have an example in pgog.Rmd, and use more descriptive commit/pull request messages?
> > 
> > 
> > Ok, I will do that
> 
> BTW the diff is coming from some Windows end-of-line characters... make sure you have the right setting for end-of-line characters:
> https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings. I just fixed the master branch in a commit

I only add one function in the divider and a example in pgog.rmd. I think there are so many diff is because I resolve the conflict using online web editor.

**Comment by xiaoyingpu** [comment]
> > > > @olivernan What exactly did you do with the `nanyy_divider_2` branch? The diff shows 27 files changed but you probably only changed a few lines in divider.R?
> > > > Also, can you write some unit tests for the `aes_checker()` function, try to have an example in pgog.Rmd, and use more descriptive commit/pull request messages?
> > > 
> > > 
> > > Ok, I will do that
> > 
> > 
> > BTW the diff is coming from some Windows end-of-line characters... make sure you have the right setting for end-of-line characters:
> > https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings. I just fixed the master branch in a commit
> 
> I only add one function in the divider and a example in pgog.rmd. I think there are so many diff is because I resolve the conflict using online web editor.

Yeah it's best not to commit those ^M things, [see](https://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it)

This is what i see when i diff this branch with master; there are ^M added compared to master. Try to remove the ^M's before merging (the ^M's are not always visible on the diffs)
image

https://stackoverflow.com/questions/82726/convert-dos-line-endings-to-linux-line-endings-in-vim

**Pull request merged**
