### PR TITLE
fix issue 87 

### PR DESCRIPTION
**Pull request by olivernan**
截屏2020-03-04下午11 42 59
截屏2020-03-04下午11 42 54
截屏2020-03-04下午11 43 07
截屏2020-03-04下午11 43 15

### CODE REVIEW

**Comment by olivernan** [comment]
May need more examples for validation

**Comment by xiaoyingpu** [comment]
@olivernan can you use those examples in pgog.Rmd as tests? If you have vdiffr tests, next time the code changes, the tests will know if new code breaks the plots. https://www.tidyverse.org/blog/2019/01/vdiffr-0-3-0/

**Comment by olivernan** [comment]
> @olivernan can you use those examples in pgog.Rmd as tests? If you have vdiffr tests, next time the code changes, the tests will know if new code breaks the plots. https://www.tidyverse.org/blog/2019/01/vdiffr-0-3-0/

Yes. All examples in the pgog.rmd works. If there anything wrong?

**Comment by xiaoyingpu** [comment]
> > @olivernan can you use those examples in pgog.Rmd as tests? If you have vdiffr tests, next time the code changes, the tests will know if new code breaks the plots. https://www.tidyverse.org/blog/2019/01/vdiffr-0-3-0/
> 
> Yes. All examples in the pgog.rmd works. If there anything wrong?

@olivernan I meant as unit tests under the `tests/` folder

**Comment by olivernan** [comment]
> > > @olivernan can you use those examples in pgog.Rmd as tests? If you have vdiffr tests, next time the code changes, the tests will know if new code breaks the plots. https://www.tidyverse.org/blog/2019/01/vdiffr-0-3-0/
> > 
> > 
> > Yes. All examples in the pgog.rmd works. If there anything wrong?
> 
> @olivernan I meant as unit tests under the `tests/` folder

I didn't know why the code failed those tests. I didn't see any clues. It shouldn't supposed to be like this. Are there any hints on that? Thanks

**Comment by xiaoyingpu** [comment]
> > > > @olivernan can you use those examples in pgog.Rmd as tests? If you have vdiffr tests, next time the code changes, the tests will know if new code breaks the plots. https://www.tidyverse.org/blog/2019/01/vdiffr-0-3-0/
> > > 
> > > 
> > > Yes. All examples in the pgog.rmd works. If there anything wrong?
> > 
> > 
> > @olivernan I meant as unit tests under the `tests/` folder
> 
> I didn't know why the code failed those tests. I didn't see any clues. It shouldn't supposed to be like this. Are there any hints on that? Thanks

hmmm which tests are failing? do you have them committed?

**Comment by olivernan** [comment]
Here is the situation. When Chen is working on the mirror feature, the master doesn't have the flip feature I am working on. So there is conflict when I try to resolve the merge conflict. Here are two possibilities. One the test case in the pgog.rmd is wrong (it is easy to fix, just gave a correct test case) Two the master branch didn't consider the flip situation.

**Comment by olivernan** [comment]
Especially this one if(mean(positions$y) == data$ymin[1]){ in geom bloc

**Comment by olivernan** [comment]
maybe need to change the condition on how to identify the flip situation

**Comment by olivernan** [comment]
Do merge this！

**Comment by olivernan** [comment]
When the checks are done, ready to be merged. All conflicts are resolved. Debug the mirror part

**Comment by olivernan** [comment]
And is there anything wrong about this plot? 
ggplot(mtcars) + geom_bloc(aes(x = mpg, fill = cyl, height = c(P(mpg | cyl))),side = "both")
截屏2020-05-05 下午7 10 11

**Pull request closed without merging**
